# Generated by Django 4.2.9 on 2024-01-25 11:17

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistributiveSubstation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('РП-4', 'Substation-4'), ('РП-5', 'Substation-5'), ('РП-6', 'Substation-6'), ('РП-7', 'Substation-7'), ('РП-8', 'Substation-8')], max_length=25)),
                ('slug', models.SlugField(unique=True)),
                ('level', models.CharField(choices=[('4.8', 'Level 4.8m'), ('8.0', 'Level 8.0m'), ('11.2', 'Level 11.2m'), ('15.4', 'Level 15.4m'), ('21.0', 'Level 21.0m'), ('25.0', 'Level 25.0m')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='MotorControlCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MCC-1', 'Motor Control Center 1'), ('MCC-2', 'Motor Control Center 2'), ('MCC-3', 'Motor Control Center 3'), ('MCC-4', 'Motor Control Center 4'), ('MCC-5', 'Motor Control Center 5'), ('MCC-6', 'Motor Control Center 6'), ('MCC-7', 'Motor Control Center 7'), ('MCC-8', 'Motor Control Center 8'), ('MCC-9', 'Motor Control Center 9'), ('MCC-10', 'Motor Control Center 10'), ('MCC-11', 'Motor Control Center 11')], max_length=25)),
                ('slug', models.SlugField(unique=True)),
                ('substation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='motor_centers', to='locator.distributivesubstation')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('slug', models.SlugField(unique=True)),
                ('label', models.ImageField(blank=True, default=None, null=True, upload_to='photos/')),
                ('round_per_minute', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3100)])),
                ('power', models.DecimalField(decimal_places=1, max_digits=4)),
                ('mcc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nodes', to='locator.motorcontrolcenter')),
            ],
        ),
    ]
