# Generated by Django 4.2.9 on 2024-02-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locator', '0002_node_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distributivesubstation',
            name='level',
            field=models.CharField(choices=[('Не вказaно', 'Не вказaно'), ('4.8', '4.8m'), ('8.0', '8.0m'), ('11.2', '11.2m'), ('15.4', '15.4m'), ('21.0', '21.0m'), ('25.6', '25.6m'), ('28.0', '28.0m'), ('32.0', '32.0m')], max_length=25),
        ),
        migrations.AlterField(
            model_name='motorcontrolcenter',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='node',
            name='level',
            field=models.CharField(choices=[('Не вказaно', 'Не вказaно'), ('4.8', '4.8m'), ('8.0', '8.0m'), ('11.2', '11.2m'), ('15.4', '15.4m'), ('21.0', '21.0m'), ('25.6', '25.6m'), ('28.0', '28.0m'), ('32.0', '32.0m')], max_length=25),
        ),
    ]
